export type Atom = {
  symbol: string;
  name: string;
  Z: number;
  period: number;
  group: number;
  category:
    | 'alkali'
    | 'alkaline'
    | 'transition'
    | 'post-transition'
    | 'metalloid'
    | 'nonmetal'
    | 'halogen'
    | 'noble'
    | 'lanthanide'
    | 'actinide';
};

export const ELEMENTS: Atom[] = [
  { symbol: 'H', name: 'Hydrogen', Z: 1, period: 1, group: 1, category: 'nonmetal' },
  { symbol: 'He', name: 'Helium', Z: 2, period: 1, group: 18, category: 'noble' },
  { symbol: 'Li', name: 'Lithium', Z: 3, period: 2, group: 1, category: 'alkali' },
  { symbol: 'Be', name: 'Beryllium', Z: 4, period: 2, group: 2, category: 'alkaline' },
  { symbol: 'B', name: 'Boron', Z: 5, period: 2, group: 13, category: 'metalloid' },
  { symbol: 'C', name: 'Carbon', Z: 6, period: 2, group: 14, category: 'nonmetal' },
  { symbol: 'N', name: 'Nitrogen', Z: 7, period: 2, group: 15, category: 'nonmetal' },
  { symbol: 'O', name: 'Oxygen', Z: 8, period: 2, group: 16, category: 'nonmetal' },
  { symbol: 'F', name: 'Fluorine', Z: 9, period: 2, group: 17, category: 'halogen' },
  { symbol: 'Ne', name: 'Neon', Z: 10, period: 2, group: 18, category: 'noble' },
  { symbol: 'Na', name: 'Sodium', Z: 11, period: 3, group: 1, category: 'alkali' },
  { symbol: 'Mg', name: 'Magnesium', Z: 12, period: 3, group: 2, category: 'alkaline' },
  { symbol: 'Al', name: 'Aluminium', Z: 13, period: 3, group: 13, category: 'post-transition' },
  { symbol: 'Si', name: 'Silicon', Z: 14, period: 3, group: 14, category: 'metalloid' },
  { symbol: 'P', name: 'Phosphorus', Z: 15, period: 3, group: 15, category: 'nonmetal' },
  { symbol: 'S', name: 'Sulfur', Z: 16, period: 3, group: 16, category: 'nonmetal' },
  { symbol: 'Cl', name: 'Chlorine', Z: 17, period: 3, group: 17, category: 'halogen' },
  { symbol: 'Ar', name: 'Argon', Z: 18, period: 3, group: 18, category: 'noble' },
  { symbol: 'K', name: 'Potassium', Z: 19, period: 4, group: 1, category: 'alkali' },
  { symbol: 'Ca', name: 'Calcium', Z: 20, period: 4, group: 2, category: 'alkaline' },
  { symbol: 'Sc', name: 'Scandium', Z: 21, period: 4, group: 3, category: 'transition' },
  { symbol: 'Ti', name: 'Titanium', Z: 22, period: 4, group: 4, category: 'transition' },
  { symbol: 'V', name: 'Vanadium', Z: 23, period: 4, group: 5, category: 'transition' },
  { symbol: 'Cr', name: 'Chromium', Z: 24, period: 4, group: 6, category: 'transition' },
  { symbol: 'Mn', name: 'Manganese', Z: 25, period: 4, group: 7, category: 'transition' },
  { symbol: 'Fe', name: 'Iron', Z: 26, period: 4, group: 8, category: 'transition' },
  { symbol: 'Co', name: 'Cobalt', Z: 27, period: 4, group: 9, category: 'transition' },
  { symbol: 'Ni', name: 'Nickel', Z: 28, period: 4, group: 10, category: 'transition' },
  { symbol: 'Cu', name: 'Copper', Z: 29, period: 4, group: 11, category: 'transition' },
  { symbol: 'Zn', name: 'Zinc', Z: 30, period: 4, group: 12, category: 'transition' },
  { symbol: 'Ga', name: 'Gallium', Z: 31, period: 4, group: 13, category: 'post-transition' },
  { symbol: 'Ge', name: 'Germanium', Z: 32, period: 4, group: 14, category: 'metalloid' },
  { symbol: 'As', name: 'Arsenic', Z: 33, period: 4, group: 15, category: 'metalloid' },
  { symbol: 'Se', name: 'Selenium', Z: 34, period: 4, group: 16, category: 'nonmetal' },
  { symbol: 'Br', name: 'Bromine', Z: 35, period: 4, group: 17, category: 'halogen' },
  { symbol: 'Kr', name: 'Krypton', Z: 36, period: 4, group: 18, category: 'noble' },
  { symbol: 'Rb', name: 'Rubidium', Z: 37, period: 5, group: 1, category: 'alkali' },
  { symbol: 'Sr', name: 'Strontium', Z: 38, period: 5, group: 2, category: 'alkaline' },
  { symbol: 'Y', name: 'Yttrium', Z: 39, period: 5, group: 3, category: 'transition' },
  { symbol: 'Zr', name: 'Zirconium', Z: 40, period: 5, group: 4, category: 'transition' },
  { symbol: 'Nb', name: 'Niobium', Z: 41, period: 5, group: 5, category: 'transition' },
  { symbol: 'Mo', name: 'Molybdenum', Z: 42, period: 5, group: 6, category: 'transition' },
  { symbol: 'Tc', name: 'Technetium', Z: 43, period: 5, group: 7, category: 'transition' },
  { symbol: 'Ru', name: 'Ruthenium', Z: 44, period: 5, group: 8, category: 'transition' },
  { symbol: 'Rh', name: 'Rhodium', Z: 45, period: 5, group: 9, category: 'transition' },
  { symbol: 'Pd', name: 'Palladium', Z: 46, period: 5, group: 10, category: 'transition' },
  { symbol: 'Ag', name: 'Silver', Z: 47, period: 5, group: 11, category: 'transition' },
  { symbol: 'Cd', name: 'Cadmium', Z: 48, period: 5, group: 12, category: 'transition' },
  { symbol: 'In', name: 'Indium', Z: 49, period: 5, group: 13, category: 'post-transition' },
  { symbol: 'Sn', name: 'Tin', Z: 50, period: 5, group: 14, category: 'post-transition' },
  { symbol: 'Sb', name: 'Antimony', Z: 51, period: 5, group: 15, category: 'metalloid' },
  { symbol: 'Te', name: 'Tellurium', Z: 52, period: 5, group: 16, category: 'metalloid' },
  { symbol: 'I', name: 'Iodine', Z: 53, period: 5, group: 17, category: 'halogen' },
  { symbol: 'Xe', name: 'Xenon', Z: 54, period: 5, group: 18, category: 'noble' },
  { symbol: 'Cs', name: 'Cesium', Z: 55, period: 6, group: 1, category: 'alkali' },
  { symbol: 'Ba', name: 'Barium', Z: 56, period: 6, group: 2, category: 'alkaline' },
  { symbol: 'La', name: 'Lanthanum', Z: 57, period: 8, group: 4, category: 'lanthanide' },
  { symbol: 'Ce', name: 'Cerium', Z: 58, period: 8, group: 5, category: 'lanthanide' },
  { symbol: 'Pr', name: 'Praseodymium', Z: 59, period: 8, group: 6, category: 'lanthanide' },
  { symbol: 'Nd', name: 'Neodymium', Z: 60, period: 8, group: 7, category: 'lanthanide' },
  { symbol: 'Pm', name: 'Promethium', Z: 61, period: 8, group: 8, category: 'lanthanide' },
  { symbol: 'Sm', name: 'Samarium', Z: 62, period: 8, group: 9, category: 'lanthanide' },
  { symbol: 'Eu', name: 'Europium', Z: 63, period: 8, group: 10, category: 'lanthanide' },
  { symbol: 'Gd', name: 'Gadolinium', Z: 64, period: 8, group: 11, category: 'lanthanide' },
  { symbol: 'Tb', name: 'Terbium', Z: 65, period: 8, group: 12, category: 'lanthanide' },
  { symbol: 'Dy', name: 'Dysprosium', Z: 66, period: 8, group: 13, category: 'lanthanide' },
  { symbol: 'Ho', name: 'Holmium', Z: 67, period: 8, group: 14, category: 'lanthanide' },
  { symbol: 'Er', name: 'Erbium', Z: 68, period: 8, group: 15, category: 'lanthanide' },
  { symbol: 'Tm', name: 'Thulium', Z: 69, period: 8, group: 16, category: 'lanthanide' },
  { symbol: 'Yb', name: 'Ytterbium', Z: 70, period: 8, group: 17, category: 'lanthanide' },
  { symbol: 'Lu', name: 'Lutetium', Z: 71, period: 8, group: 18, category: 'lanthanide' },
  { symbol: 'Hf', name: 'Hafnium', Z: 72, period: 6, group: 4, category: 'transition' },
  { symbol: 'Ta', name: 'Tantalum', Z: 73, period: 6, group: 5, category: 'transition' },
  { symbol: 'W', name: 'Tungsten', Z: 74, period: 6, group: 6, category: 'transition' },
  { symbol: 'Re', name: 'Rhenium', Z: 75, period: 6, group: 7, category: 'transition' },
  { symbol: 'Os', name: 'Osmium', Z: 76, period: 6, group: 8, category: 'transition' },
  { symbol: 'Ir', name: 'Iridium', Z: 77, period: 6, group: 9, category: 'transition' },
  { symbol: 'Pt', name: 'Platinum', Z: 78, period: 6, group: 10, category: 'transition' },
  { symbol: 'Au', name: 'Gold', Z: 79, period: 6, group: 11, category: 'transition' },
  { symbol: 'Hg', name: 'Mercury', Z: 80, period: 6, group: 12, category: 'transition' },
  { symbol: 'Tl', name: 'Thallium', Z: 81, period: 6, group: 13, category: 'post-transition' },
  { symbol: 'Pb', name: 'Lead', Z: 82, period: 6, group: 14, category: 'post-transition' },
  { symbol: 'Bi', name: 'Bismuth', Z: 83, period: 6, group: 15, category: 'post-transition' },
  { symbol: 'Po', name: 'Polonium', Z: 84, period: 6, group: 16, category: 'post-transition' },
  { symbol: 'At', name: 'Astatine', Z: 85, period: 6, group: 17, category: 'halogen' },
  { symbol: 'Rn', name: 'Radon', Z: 86, period: 6, group: 18, category: 'noble' },
  { symbol: 'Fr', name: 'Francium', Z: 87, period: 7, group: 1, category: 'alkali' },
  { symbol: 'Ra', name: 'Radium', Z: 88, period: 7, group: 2, category: 'alkaline' },
  { symbol: 'Ac', name: 'Actinium', Z: 89, period: 9, group: 4, category: 'actinide' },
  { symbol: 'Th', name: 'Thorium', Z: 90, period: 9, group: 5, category: 'actinide' },
  { symbol: 'Pa', name: 'Protactinium', Z: 91, period: 9, group: 6, category: 'actinide' },
  { symbol: 'U', name: 'Uranium', Z: 92, period: 9, group: 7, category: 'actinide' },
  { symbol: 'Np', name: 'Neptunium', Z: 93, period: 9, group: 8, category: 'actinide' },
  { symbol: 'Pu', name: 'Plutonium', Z: 94, period: 9, group: 9, category: 'actinide' },
  { symbol: 'Am', name: 'Americium', Z: 95, period: 9, group: 10, category: 'actinide' },
  { symbol: 'Cm', name: 'Curium', Z: 96, period: 9, group: 11, category: 'actinide' },
  { symbol: 'Bk', name: 'Berkelium', Z: 97, period: 9, group: 12, category: 'actinide' },
  { symbol: 'Cf', name: 'Californium', Z: 98, period: 9, group: 13, category: 'actinide' },
  { symbol: 'Es', name: 'Einsteinium', Z: 99, period: 9, group: 14, category: 'actinide' },
  { symbol: 'Fm', name: 'Fermium', Z: 100, period: 9, group: 15, category: 'actinide' },
  { symbol: 'Md', name: 'Mendelevium', Z: 101, period: 9, group: 16, category: 'actinide' },
  { symbol: 'No', name: 'Nobelium', Z: 102, period: 9, group: 17, category: 'actinide' },
  { symbol: 'Lr', name: 'Lawrencium', Z: 103, period: 9, group: 18, category: 'actinide' },
  { symbol: 'Rf', name: 'Rutherfordium', Z: 104, period: 7, group: 4, category: 'transition' },
  { symbol: 'Db', name: 'Dubnium', Z: 105, period: 7, group: 5, category: 'transition' },
  { symbol: 'Sg', name: 'Seaborgium', Z: 106, period: 7, group: 6, category: 'transition' },
  { symbol: 'Bh', name: 'Bohrium', Z: 107, period: 7, group: 7, category: 'transition' },
  { symbol: 'Hs', name: 'Hassium', Z: 108, period: 7, group: 8, category: 'transition' },
  { symbol: 'Mt', name: 'Meitnerium', Z: 109, period: 7, group: 9, category: 'transition' },
  { symbol: 'Ds', name: 'Darmstadtium', Z: 110, period: 7, group: 10, category: 'transition' },
  { symbol: 'Rg', name: 'Roentgenium', Z: 111, period: 7, group: 11, category: 'transition' },
  { symbol: 'Cn', name: 'Copernicium', Z: 112, period: 7, group: 12, category: 'transition' },
  { symbol: 'Nh', name: 'Nihonium', Z: 113, period: 7, group: 13, category: 'post-transition' },
  { symbol: 'Fl', name: 'Flerovium', Z: 114, period: 7, group: 14, category: 'post-transition' },
  { symbol: 'Mc', name: 'Moscovium', Z: 115, period: 7, group: 15, category: 'post-transition' },
  { symbol: 'Lv', name: 'Livermorium', Z: 116, period: 7, group: 16, category: 'post-transition' },
  { symbol: 'Ts', name: 'Tennessine', Z: 117, period: 7, group: 17, category: 'halogen' },
  { symbol: 'Og', name: 'Oganesson', Z: 118, period: 7, group: 18, category: 'noble' },
];
